### PR TITLE
Fixed broken image for articles from "The Times"

### LINKED ISSUE #97: [BUG] Broken image for articles from "The Times"
### What bug did you encounter?

When checking a cool frontend app someone built for this site, I noticed that the articles from "The Times" were not showing an image **or** the back-up image we set.

### What did you expect to happen?

The backup image. (site logo).

### Screenshots

image

### Additional information

I think we need a better check on the image in the `src/controller/api/newsAPIController.js` file.

Currently it only checks for a `null` and subs in the default image. We need a check to ensure the string starts with `http` _otherwise then_ sub in the default image as that will catch `null` values too.

### PR DESCRIPTION
**Pull request by MuizU**
- Fixes #97 
- Added regex check for image URL in `src/controller/api/newsAPIController.js`

### CODE REVIEW

File: src/controller/api/newsAPIController.js [hunk 1]
```diff
@@ -22,7 +22,10 @@ sources.forEach(async (source) => {
         title: returned.title,
         url: source.base + returned.url,
         source: source.name,
-        image: returned.image ?? defaultImage,
+        image:
+          !!returned.image && !!/^((http|https):\/\/)/.test(returned.image)
```
Comment (MizouziE) [inline src/controller/api/newsAPIController.js:26]: This does work, but it would be more simple (I think) to just use **only** the `RegExp.test(returned.image)` here as the check, because;
- Casting to Boolean isn't necessary as the method returns a Boolean anyway
- No need to check it exists as well. When it doesn't exist it returns `undefined` which fails the "starts with http|https" test right away.

e.g.
```js
        image:
          /^((http|https):\/\/)/.test(returned.image)
          ? returned.image
          : defaultImage,
```

**Review by MizouziE — CHANGES_REQUESTED** [review]
Somewhere around line 65 ~ 68 there is another instance of the same problem for the single source controller function.

Add the same solution there and I think we're good to go.

**Comment by MizouziE** [comment]
Hey @MuizU , would you like me to move this over to a new branch and open it up for someone to finish off?

**Comment by MuizU** [comment]
> Hey @MuizU , would you like me to move this over to a new branch and open it up for someone to finish off?

Hi @MizouziE, I made the changes, but didn't push it yet, will be doing it later today. Was caught up in something else apologies for the delay.

**Comment by MizouziE** [comment]
No problem at all man! I just wanted to check. I appreciate it.

**Review by MizouziE — APPROVED** [review]
Perfect. Thank you very much! 💪
